### ISSUE TITLE
Build an SMS Delivery Service with SQS and SNS

### ISSUE THREAD

**Issue by Auwalms** [debo-centbit/notification#1]
**Expectation:** 

Build a lambda function that polls message from sqs, create an sms template and publish the message to SNS

**Pseudocode:**

```
//poll message from sqs
//generate sms template
//use SNS to send the message
```

**Acceptance Criteria**

- [ ] Function must be reusable and written in javascript/typescript
- [ ] Function should be able to fetch poll messages from SQS
- [ ] Function should be able to create an SMS template
- [ ] Function should be able to fetch publish messages from SNS
- [ ] Unit tests must be written for every component using [Jest Testing Library](https://jestjs.io/) with a test coverage of >80%
- [ ] Integration test should be written using the above-stated library. See [Example](https://dev.to/ali_adeku/guide-to-writing-integration-tests-in-express-js-with-jest-and-supertest-1059) for guidance.

**Comment by OlawaleP** [comment]
Acknowledged

**Comment by jezes70** [comment]
there is nothing in the repo till now?
